# Generated by Django 4.2.7 on 2023-11-10 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('size', models.PositiveIntegerField()),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('mime_version', models.CharField(blank=True, max_length=50, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('username', 'hostname')},
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('from', 'FROM'), ('to', 'TO'), ('cc', 'CC'), ('bcc', 'BCC'), ('reply_to', 'REPLY TO')], max_length=10)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailbox.emailheader')),
                ('email_router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailbox.emailrouter')),
            ],
        ),
    ]
