version: "3.12"
services:
  db:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_DB: universal
      POSTGRES_PASSWORD: password
      
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
