# Generated by Django 4.2.7 on 2023-11-08 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UniversalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('concepts', models.ManyToManyField(related_name='entities', to='ontology.concept')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('applicable_from', models.ManyToManyField(related_name='applicable_from', to='ontology.concept')),
                ('applicable_to', models.ManyToManyField(related_name='applicable_to', to='ontology.concept')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='ontology.universalentity')),
                ('entity_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='ontology.universalentity')),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.relationshiptype')),
            ],
        ),
    ]
