# Generated by Django 4.2.7 on 2023-11-08 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='ontology.concept'),
        ),
        migrations.AddField(
            model_name='universalentity',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universalentity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ontology.universalentity'),
        ),
    ]
