# Generated by Django 4.2.7 on 2023-11-09 18:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ground_zero',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='personaldocument',
            name='expiry_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='personaldocument',
            name='issue_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='personaldocument',
            name='issuer_authority',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
