# Generated by Django 4.2.7 on 2023-11-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_address_ground_zero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileaccount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldocument',
            name='issuer_authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
